---
name: Alien-Prototype-Window
version: 1.3.3
author:
  - Graham TerMarsch (cpan@howlingfrog.com)
abstract: installing and finding Prototype Window Class
license: perl
resources:
  license: ~
requires:
  Alien::scriptaculous: 1.7.1.1_03
  perl: 5.6.0
build_requires:
  Archive::Zip: 0
  Test::Exception: 0
provides:
  Alien::Prototype::Window:
    file: lib/Alien/Prototype/Window.pm
    version: 1.3.3
generated_by: Module::Build version 0.32
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
